### ISSUE TITLE
Нельзя перейти на следующий шаг

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#11]
**Описание**
Нельзя перейти на следующий шаг при выборе чекбокса "Нет отчества"

**Шаги воспроизведения**
1. 1. Перейти по ссылке #/wizard/preschool/childrenStep
2. Заполнить поля
3. Кликнуть чекбокс "Нет отчества"
4. Кликнуть "Далее"

**Ожидаемый результат**
Переход на следующий шаг
Фактический результат: Кнопка "Далее" не активна.

 - OS: [Win7 x64]
 - Browser: [chrome, safari firefoxe, IE 10]
 - Version [chrome 69.0.3497.100 ]

**Дополнительный контекст**

**Comment by VladimirAbizov** [comment]
реализовано в ветке abizov
