### ISSUE TITLE
Невозможно перейти на следующий шаг при выборе родственной связи : мать/отец/опекун

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#12]
**Описание**
Невозможно перейти на следующий шаг при выборе родственной связи : мать/отец/опекун

**Шаги воспроизведения**
1. Перейти по ссылке #/wizard/preschool/parentStep
2. Заполнить данные
3. В раскрывающемся списке "Родственная связь" выбрать мать/отец/опекун
4. Кликнуть "Далее"

**Ожидаемый результат**
Переход на следующий шаг
Фактический результат: Кнопка "Далее" не активна

- OS: [Win7 x64]
- Browser: [chrome, safari firefoxe, IE 10]
- Version [chrome 69.0.3497.100 ]

**Дополнительный контекст**
![image](https://user-images.githubusercontent.com/36604466/46143909-28184f00-c264-11e8-90bf-fd9f63e09d28.png)

**Comment by ArtemYazynin** [comment]
master ветка
