### ISSUE TITLE
Отображаются только школы вместо садов при выборе ДОО

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#13]
**Описание**
Отображаются только школы вместо садов при выборе ДОО

**Шаги воспроизведения**
1. Перейти по ссылке #/wizard/preschool/preschoolInstitutionStep
2. Кликнуть на раскрывающийся список "ДОО"

**Ожидаемый результат**
В раскрывающемся списке - сады
Фактический результат: В раскрывающемся списке - школы

OS: [Win7 x64]
Browser: [chrome, safari firefoxe, IE 10]
Version [chrome 69.0.3497.100 ]

**Дополнительный контекст**
![image](https://user-images.githubusercontent.com/36604466/46144921-1b492a80-c267-11e8-8b44-9a8901bb5975.png)

**Comment by ArtemYazynin** [comment]
master ветка

**Comment by ArtemYazynin** [comment]
Не заполнялся тип заявления в объекте session storage. 
Теперь наличие типа заявления проверяется при каждом обновлении объекта.

**Comment by AlenaKuznecova63** [comment]
fixed
