### ISSUE TITLE
Не отображаются группа/класс в раскрывающемся списке 

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#3]
**Describe the bug**
Не отображаются группа/класс в раскрывающемся списке при выборе образовательной организации "Якорек"/" Ручеек"/" Фиалка"/" Росинка"/" Снежинка" 

**To Reproduce**
1.Перейти по ссылке #/wizard/preschool/currentEducationPlaceStep
2.В поле Муниципалитет выбрать "Городской округ Балашиха" 
3.В поле Тип образовательной организации выбрать  "Дошкольная образовательная огранизация"
4.В поле Образовательная организация выбрать "Якорек"/" Ручеек"/" Фиалка"/" Росинка"/" Снежинка" 
5.Кликнуть  на поле "Группы/Класс"

**Expected behavior**
В раскрывающемся списке отображаются группы/классы
Фактический результат:  Группы не отображаются в раскрывающемся списке

Desktop (please complete the following information):
OS: [Win7 x64]
Browser [chrome, safari firefoxe, IE 10]
Version [chrome 69.0.3497.100 ]

**Comment by ArtemYazynin** [comment]
**Обсудил с аналитиком**, решили выбор группы сделать не обязательным.
Если у ОО нет групп, должна быть возможность перейти на следующий шаг и зарегистрировать заявление

**Comment by AlenaKuznecova63** [comment]
fixed
