### ISSUE TITLE
Отсутствует чекбокс  " Не оповещать" 

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#4]
**Describe the bug**
Отсутствует чекбокс  " Не оповещать" при заполнении контактной информации

**To Reproduce**
1.Перейти по ссылке #/wizard/preschool/contactInfoStep\

**Expected behavior**
Присутствует чекбокс: " Не оповещать" 
Фактический результат:  Отсутствует чекбокс  " Не оповещать"

Desktop (please complete the following information):
OS: [Win7 x64]
Browser [chrome, safari firefoxe, IE 10]
Version [chrome 69.0.3497.100 ]

**Comment by ArtemYazynin** [comment]
В спеке заявлено, нужно реализовать.
При переводе чекбокса в отмеченное состояние, нужно очищать input поля и сбрасывать чекбоксы с типом оповещения.
