### ISSUE TITLE
Список садов не открывается после выбора сада

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#8]
**Describe the bug**
Список садов не открывается после выбора сада

**To Reproduce**

1. Перейти по ссылке #/wizard/preschool/preschoolInstitutionStep
2. Кликнуть на поле ДОО
3. Выбрать сад
4. Кликнуть повторно на поле ДОО

**Expected behavior**
Разворачивается расскрывающийся список с садом
Фактический результат :  Раскрывающийся список с садом не разворачивается

Desktop (please complete the following information):
OS: [Win7 x64]
Browser [chrome, safari firefoxe, IE 10]
Version [chrome 69.0.3497.100 ]

**Comment by ArtemYazynin** [comment]
взял на доработку
