### ISSUE TITLE
Можно выбрать более 3-х садов 

### ISSUE THREAD

**Issue by AlenaKuznecova63** [ArtemYazynin/es3#9]
**Describe the bug**
Можно выбрать более 3-х садов при возврате к шагу выбора ДОО

**To Reproduce**
1. Перейти по ссылке #/wizard/preschool/preschoolInstitutionStep
2. Выбрать три сада
3. Кликнуть кнопку "Далее"
4. Вернуться к шагу выбора ДОО
5. Попытаться выбрать сад

**Expected behavior**
Сообщение об ошибке (максимальное кол-во желаемых ДОО - 3)
Фактический результат:  Добавляется четвертый сад

Desktop (please complete the following information):
OS: [Win7 x64]
Browser [chrome, safari firefoxe, IE 10]
Version [chrome 69.0.3497.100 ]

**Comment by VladimirAbizov** [comment]
реализовано в ветке master

**Comment by AlenaKuznecova63** [comment]
fixed
